jwt.secret=c3VwZXItc2VndXJhLWNoYXZlLWRlLWRlc2Vudm9sdmltZW50by1xdWUtbmFvLWRldmUtc2VyLWNvbXBhcnRpbGhhZGEK

# Porta do servidor
server.port=8081

# Configuração H2 para desenvolvimento (banco em memória)
spring.datasource.url=jdbc:h2:mem:gestorcompras
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

# Configuração JPA para H2
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Console do H2 (opcional - para visualizar os dados)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Flyway desabilitado para H2 (vamos usar ddl-auto)
spring.flyway.enabled=false