spring.profiles.active=dev
logging.level.org.springframework.security=DEBUG
server.port=8081

# ==============================================================
# MONITORAMENTO E MÉTRICAS (PROMETHEUS)
# ==============================================================
# Habilita todos os endpoints do actuator, incluindo prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics

# Detalhes de saúde
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# Métricas da JVM e Processo
management.metrics.tags.application=gestor-compras
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.sla.http.server.requests=50ms,100ms,200ms,500ms,1s,5s

# ==============================================================
# LOGGING (LOKI / PROMTAIL)
# ==============================================================
# Caminho do arquivo de log que será lido pelo Promtail
# O Docker Compose mapeia ./gestor-compras-backend/logs para o container do Promtail
logging.file.name=logs/gestor-compras.log
logging.file.max-history=7
logging.file.max-size=10MB

# Formato do Log (deve bater com o Regex do Promtail)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %thread --- [%-40.40logger{39}] : %msg%n
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level) %clr(%thread) %clr(---) %clr([%-40.40logger{39}]) %clr(:) %msg%n
